package com.example.SurveyMicro.Enitity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an Answer option for a question, including optional suggestions.
 */
@Entity
@Table(name = "answer")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Answer {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long optionId; // Unique identifier for the answer option

    private String optionText; // Text of the answer option
    private String suggestion; // Optional suggestion related to the answer option

    // Getters and setters are auto-generated by @Data
}
