package com.example.SurveyMicro.Enitity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * Represents a Survey entity with basic survey details.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Survey {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long surveyId; // Unique identifier for the survey

    private String domainName; // Domain of the survey
    private String companyName; // Name of the company conducting the survey
    private String email; // Email address for the survey
    private String setName; // Name of the survey set
    @Enumerated(EnumType.STRING)
    private SurveyStatus status=SurveyStatus.PENDING; // Current status of the survey (e.g., Initiated, Accepted, Rejected)
    private String questionIds; // Comma-separated string of question IDs associated with the survey

    // Getters and setters are auto-generated by @Data
}
