server:
  port: 8082
spring:
  application:
    name: assessment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/assessmentdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
