package com.ust.SurveyMicro.Enitity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents an Assessment entity, including a set of questions and metadata about the assessment.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Assessment {
    @Id
    private Long setId; // Unique identifier for the assessment set

    private String setName; // Name of the assessment set
    private String createdBy; // Name of the user who created the assessment
    private String updatedBy; // Name of the user who last updated the assessment (defaulted to "admin")
    private String domain; // Domain of the assessment
    private String status; // Current status of the assessment

    private LocalDateTime createdTimestamp; // Timestamp when the assessment was created
    private LocalDateTime updatedTimestamp; // Timestamp when the assessment was last updated

    @OneToMany(cascade = CascadeType.ALL)
    private List<Question> questions; // List of questions included in the assessment

    @PrePersist
    protected void onCreate() {
        createdTimestamp = LocalDateTime.now(); // Set the creation timestamp
        updatedTimestamp = LocalDateTime.now(); // Set the update timestamp
    }

    @PreUpdate
    protected void onUpdate() {
        updatedTimestamp = LocalDateTime.now(); // Update the timestamp on update
    }

    // Getters and setters are auto-generated by @Data
}
